ln -s ../"Acid#1.unosyp"                                               21.unosyp
ln -s ../"Acid#10.unosyp"                                              22.unosyp
ln -s ../"Acid#2.unosyp"                                               23.unosyp
ln -s ../"Acid#3.unosyp"                                               24.unosyp
ln -s ../"Acid#4.unosyp"                                               25.unosyp
ln -s ../"Acid#5.unosyp"                                               26.unosyp
ln -s ../"Acid#6.unosyp"                                               27.unosyp
ln -s ../"Acid#7.unosyp"                                               28.unosyp
ln -s ../"Acid#8.unosyp"                                               29.unosyp
ln -s ../"Acid#9.unosyp"                                               30.unosyp
ln -s ../"CrazyKickFx.unosyp"                                          31.unosyp
ln -s ../"LFOFilterBass.unosyp"                                        32.unosyp
ln -s ../"LFORateBass.unosyp"                                          33.unosyp
ln -s ../"MeditativeSynth.unosyp"                                      34.unosyp
ln -s ../"PowerSynth.unosyp"                                           35.unosyp
ln -s ../"PsyBassFx.unosyp"                                            36.unosyp
ln -s ../"PsyFx#1.unosyp"                                              37.unosyp
ln -s ../"PsyFx#2.unosyp"                                              38.unosyp
ln -s ../"PsyFx#3.unosyp"                                              39.unosyp
ln -s ../"PsyFx#4.unosyp"                                              40.unosyp
ln -s ../"PulseBass.unosyp"                                            41.unosyp
ln -s ../"PulseBassBPF.unosyp"                                         42.unosyp
ln -s ../"RandomMelody.unosyp"                                         43.unosyp
ln -s ../"RandomMelody#2.unosyp"                                       44.unosyp
ln -s ../"ResonanceBass.unosyp"                                        45.unosyp
ln -s ../"ResonanceBass#2.unosyp"                                      46.unosyp
ln -s ../"SignalSynth.unosyp"                                          47.unosyp
ln -s ../"StrangeSynth.unosyp"                                         48.unosyp
ln -s ../"TremoloBass.unosyp"                                          49.unosyp
ln -s ../"TremoloBass#2.unosyp"                                        50.unosyp
ln -s ../"WalkingBass.unosyp"                                          51.unosyp
